### ISSUE TITLE
Japanese (日本語) <ja.cfg>

### ISSUE THREAD

**Issue by zer0Kerbal** [net-lisias-ksp/GPOSpeedPump#20]
# Localization - ![日本語][JA] Japanese(日本語) <ja.cfg>

## GitHub

* [x] assign
  * [x] zer0Kerbal
  * [x] Repo Localization Project
  * [x] Label: localization
  * [x] Label: help-wanted
  * [x] Milestone: Localization - Master

### GameData

* [x] add  Localization\[ja.cfg] 🗃️

### Translation

* [x] ![日本語][JA] Japanese(日本語) <ja.cfg>

### Documentation

* [x] Update [readme.md] 🔢
* [x] Update [release.md] 🧾

### Wiki

* [x] Update docs/[localization.md]

## Update Social Media

* [x] GitHub (automated) (zer0Kerbal/zer0Kerbal)
* [x] CurseForge
* [x] Reddit
* [x] Twitter @zer0Kerbal
* [x] Forum
* [x] Patreon
* [x] SpaceDock
* [x] CKAN (automated)

[URL:lclztn]: https://github.com/zer0Kerbal/lclztn/blob/master/readme.md "Localization"
[URL:qs]: https://github.com/zer0Kerbal/lclztn/blob/master/quickstart.md "Quick Start"

[JA]: https://raw.githubusercontent.com/zer0Kerbal/zer0Kerbal/zed'K/Localization/img/Japanese-flag-sm.png "日本語"

**Comment by Lisias** [comment]
Translation merged by https://github.com/net-lisias-ksp/GPOSpeedPump/pull/38

**Comment by Lisias** [comment]
Closed by Pull Request https://github.com/net-lisias-ksp/GPOSpeedPump/pull/38
