### ISSUE TITLE
Spanish (Español) <es-es.cfg>

### ISSUE THREAD

**Issue by zer0Kerbal** [net-lisias-ksp/GPOSpeedPump#23]
# Localization - ![Español][ES] Spanish (Español) <es-es.cfg>

## GitHub

* [x] assign
  * [x] zer0Kerbal
  * [x] Repo Localization Project
  * [x] Label: localization
  * [x] Label: help-wanted
  * [x] Milestone: Localization - Master

### GameData

* [x] add  Localization\[es-es.cfg] 🗃️

### Translation

* [x] ![Español][ES] Spanish (Español) <es-es.cfg>

### Documentation

* [x] Update [readme.md] 🔢
* [x] Update [release.md] 🧾

### Wiki

* [x] Update docs/[Localization.md]

## Update Social Media

* [x] GitHub (automated) (zer0Kerbal/zer0Kerbal)
* [x] CurseForge
* [x] Reddit
* [x] Twitter @zer0Kerbal
* [x] Forum
* [x] Patreon
* [x] SpaceDock
* [x] CKAN (automated)

[URL:lclztn]: https://github.com/zer0Kerbal/lclztn/blob/master/readme.md "Localization"
[URL:qs]: https://github.com/zer0Kerbal/lclztn/blob/master/quickstart.md "Quick Start"

[ES]: https://raw.githubusercontent.com/zer0Kerbal/zer0Kerbal/zed'K/Localization/img/Spanish-flag-sm.png "Español"

**Comment by Lisias** [comment]
I had merged the Pull Request. I think we can close it now?

**Comment by zer0Kerbal** [comment]
#34 closes #23
