### ISSUE TITLE
Brazilian Portuguese (Português Brasil) <pt-br.cfg>

### ISSUE THREAD

**Issue by zer0Kerbal** [net-lisias-ksp/GPOSpeedPump#25]
# Localization - ![Português Brasil][BR] Brazilian Portuguese (Português Brasil) <pt-br.cfg>

## GitHub

* [x] assign
  * [x] zer0Kerbal
  * [x] Repo Localization Project
  * [x] Label: localization
  * [x] Label: help-wanted
  * [x] Milestone: Localization - Master

### GameData

* [x] add  Localization\[pr-br.cfg] 🗃️

### Translation

* [x] ![Português Brasil][BR] Brazilian Portuguese (Português Brasil) <pt-br.cfg>

### Documentation

* [x] Update [readme.md] 🔢
* [x] Update [release.md] 🧾

### Wiki

* [x] Update docs/[localization.md]

## Update Social Media

* [ ] GitHub (automated) (zer0Kerbal/zer0Kerbal)
* [ ] CurseForge
* [ ] Reddit
* [ ] Twitter @zer0Kerbal
* [ ] Forum
* [ ] Patreon
* [ ] SpaceDock
* [ ] CKAN (automated)

[URL:lclztn]: https://github.com/zer0Kerbal/lclztn/blob/master/readme.md "Localization"
[URL:qs]: https://github.com/zer0Kerbal/lclztn/blob/master/quickstart.md "Quick Start"

[BR]: https://raw.githubusercontent.com/zer0Kerbal/zer0Kerbal/zed'K/Localization/img/Brazilian-flag-sm.png "Brazil"

**Comment by Lisias** [comment]
I'm working on it.

**Comment by zer0Kerbal** [comment]
> I'm working on it.
*chuckle*

👍 

all good

**Comment by Lisias** [comment]
Implemented on commits https://github.com/net-lisias-ksp/GPOSpeedPump/commit/1f5a8374bb9613e5ad83f2a3fc0b2300e22e1ac2, https://github.com/net-lisias-ksp/GPOSpeedPump/commit/2ec686ac622541187cba4e488554badc01766bff and https://github.com/net-lisias-ksp/GPOSpeedPump/commit/e0903b153e5cf62a251276bc8750b4393e001780 .

![screenshot77](https://user-images.githubusercontent.com/64334/190566933-075b4c2e-fb7d-43d5-8cbb-339b9a4a28f1.png)

**Comment by zer0Kerbal** [comment]
@Lisias "I love it when a plan comes together!"
