### ISSUE TITLE
CKAN

### ISSUE THREAD

**Issue by logitechQ** [net-lisias-ksp/GPOSpeedPump#5]
Hi hi! Would you kindly upload this on spacedock so that Ckan can point to the updated version? It is still pointing to the old thread and is not the same version as the one on curseforge/Github.

Thank you very much!

**Comment by Lisias** [comment]
Probably on the next weekend . Real Life™ got into the way

**Comment by Lisias** [comment]
(sigh) 

@logitechQ , this is more a rant that a explanation, but I'm taking extra precautions on everything I do on SpaceDock CKAN due this:

https://github.com/KSP-CKAN/NetKAN/pull/9076

Supporting CKAN is a nightmare and a pain. Some "big guy" screws you **big time** on a mistake **he** did but that ended up hitting you, and **you** are held responsible and ends up being forced to accept working for free as beta tester to avoid having **your** add'on blocked as a conflict - screwing your users.

So, **everything** I'm going to publish on SpaceDock is (as demanded by the guys) being tested to the maximum extension I'm able to. And this takes a lot of time, that I don't have consistently.

I'm sorry things get into this point, but as it appears, it's this way or it's the highway - there's no point on rushing up publishing GPO/SP into CKAN only to get it flagged as conflict due some bug (no matter being mine or from 3rd parties - this is really obnoxious), what end up having it unavailable the same for most users.

**Comment by Lisias** [comment]
Forgot about this one. GPO/SP is now on SpaceDock. So I'm closing this.
