### ISSUE TITLE
Code Localization

### ISSUE THREAD

**Issue by zer0Kerbal** [net-lisias-ksp/GPOSpeedPump#8]
# Code Localization

* [ ] settings
* [x] GUI
* [x] screen
* [x] PAW
* [ ] InstallChecker
* [ ] ?

**Comment by zer0Kerbal** [comment]
all mine. :D

**Comment by Lisias** [comment]
I'm merging this, and publishing it under 1.9.0.6 , 

Localizing Install Checker will need to be taclked down on KSPe, as the code is on that library: https://github.com/net-lisias-ksp/KSPe/issues/33

(so this issue is blocked by it until I implement support there)

**Comment by Lisias** [comment]
In time, I didn't knew about these "tasks" stunt on github! **VERY NICE!!**

**Comment by Lisias** [comment]
May I suggest changing the localization prefix from `GPO` to `GPOSF` ?

We are using `GPOSF` everywhere, and normalizing the prefixes will make things easier on the long run.

**Comment by zer0Kerbal** [comment]
> May I suggest changing the localization prefix from `GPO` to `GPOSF` ?
> 
> We are using `GPOSP` everywhere, and normalizing the prefixes will make things easier on the long run.
> 
> edit: check this commit: [9214f41](https://github.com/net-lisias-ksp/GPOSpeedPump/commit/9214f411cfc54f2ce30ac2f2bfeb0a977617ea6a)

agree. good suggestion, and I don't know why I didn't do it that way in the first place! 🤔
